name: Android CI

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Test engine
      run: ./gradlew :engine:test

    - name: Test game
      run: ./gradlew :game:allTest

    - name: Build Android app
      run: ./gradlew :androidApp:build
