name: Android CI

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Test all modules
        run: ./gradlew test allTest

      - name: Build desktop app
        run: ./gradlew :app-desktop:build

      - name: Build Android app
        run: ./gradlew :app-android:build
